#!/usr/bin/env python3
"""Render auditable LaTeX fragments for the revised main evidence.

All displayed counts and bounds are read from the clean-matrix, assign-search,
and independently audited five-refiner JSON reports.  The generated fragments
are intentionally small enough to inspect in the submission artifact.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXP = ROOT / "experiments"
PAPER = ROOT / "paper"
CLEAN = EXP / "glm4flash_repaired_matrix_final_20260910_analysis.json"
SEARCH = EXP / "assign_search_intervention_20260909/analysis.json"
REFINERS = EXP / "shared_refiner5_temporal_20260909/analysis_audited.json"
CAUSAL_RECOVERY = (EXP / "glm4flash_repaired_matrix_causal_recovery_20260910" /
                   "manifest.json")

CELLS = {
    "code/tight": "CodeTight",
    "code/loose": "CodeLoose",
    "math/tight": "MathTight",
    "math/loose": "MathLoose",
}
ARMS = {
    "arm1_assign": ("Assign", "assign"),
    "arm2_samepolicy": ("Same", "same-policy"),
    "arm3_diffpolicy": ("Diff", "different-policy"),
}
REFINER_LABELS = {
    "standard": "standard",
    "targeted": "targeted",
    "conservative": "conservative",
    "long_form": "long-form",
    "independent_reconcile": "independent+reconcile",
}


def dec(value: float, digits: int = 3) -> str:
    out = f"{abs(value):.{digits}f}"
    return out[1:] if out.startswith("0") else out


def signed(value: float, digits: int = 3) -> str:
    return ("+" if value >= 0 else "-") + dec(value, digits)


def pct(value: float) -> str:
    return f"{100 * value:.1f}\\%"


def command(name: str, value: object) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


def main() -> None:
    clean = json.loads(CLEAN.read_text())
    search = json.loads(SEARCH.read_text())
    refiners = json.loads(REFINERS.read_text())
    causal_recovery = json.loads(CAUSAL_RECOVERY.read_text())

    macros: list[str] = [
        "% Generated by scripts/render_main_evidence.py; do not hand edit.",
    ]
    matrix_rows: list[str] = []
    lambda_rows: list[str] = []
    total_defects = 0
    total_reserve = 0
    total_assign_acceptance_breaks = 0
    total_calls = 0
    total_tokens = 0
    for key, prefix in CELLS.items():
        cell = clean["cells"][key]
        reference = cell["reference"]
        assert cell["n_tasks"] == 150 and cell["n_seeds"] == 3, key
        assert reference["rows"] == 450, (key, reference["rows"])
        total_defects += cell["executor_defects"]["reference"]
        total_calls += reference["calls"]
        total_tokens += reference["tokens"]
        macros.extend([
            command(prefix + "ReferenceAccuracy", dec(reference["accuracy"])),
            command(prefix + "ReferenceCalls", reference["calls"]),
            command(prefix + "ReferenceTokens", reference["tokens"]),
        ])
        family, tier = key.split("/")
        for index, (arm_key, (arm_prefix, arm_label)) in enumerate(ARMS.items()):
            arm = cell["arms"][arm_key]
            assert arm["effective_tasks"] == 150, (key, arm_key)
            assert arm["matched_pairs"] == 450, (key, arm_key)
            assert sum(arm["status_counts"].values()) == 450, (key, arm_key)
            total_defects += cell["executor_defects"][arm_key]
            total_calls += arm["calls"]
            total_tokens += arm["tokens"]
            reserve = arm["status_counts"].get("reserve_rejected", 0)
            total_reserve += reserve
            if arm_key == "arm1_assign":
                total_assign_acceptance_breaks += arm["acceptance_path_breakage_events"]
            point, lo, hi = arm["accuracy_delta_ci95"]
            base = prefix + arm_prefix
            macros.extend([
                command(base + "Delta", signed(point)),
                command(base + "DeltaLo", signed(lo)),
                command(base + "DeltaHi", signed(hi)),
                command(base + "Repairs", arm["repair_events"]),
                command(base + "RepairDen", arm["repair_denominator"]),
                command(base + "Breaks", arm["breakage_events"]),
                command(base + "BreakDen", arm["breakage_denominator"]),
                command(base + "AcceptBreaks", arm["acceptance_path_breakage_events"]),
                command(base + "RejectBreaks", arm["rejection_path_breakage_events"]),
                command(base + "ReserveRejects", reserve),
                command(base + "Calls", arm["calls"]),
                command(base + "Tokens", arm["tokens"]),
            ])
            matrix_rows.append(
                f"{family + '/' + tier if index == 0 else ''} & "
                f"{arm_label} & " + "$" +
                f"{signed(point)}\\,[{signed(lo)},{signed(hi)}]$ & "
                f"{arm['repair_events']}/{arm['repair_denominator']} & "
                f"{arm['breakage_events']}/{arm['breakage_denominator']} & "
                f"{arm['acceptance_path_breakage_events']} & "
                f"{arm['calls']:,} & {arm['tokens'] / 1000:.0f}k \\\\"
            )
        matrix_rows.append(r"\addlinespace[2pt]")
        value = cell["lambda_star_assign_vs_diffpolicy"]
        assign = cell["arms"]["arm1_assign"]
        diff = cell["arms"]["arm3_diffpolicy"]
        if value is None:
            value_label = "--"
        elif value <= 0:
            value_label = "$0$ (assign dominates)"
        else:
            value_label = dec(value, 2)
        lambda_rows.append(
            f"{family}/{tier} & {assign['repair_events']}/{assign['breakage_events']} & "
            f"{diff['repair_events']}/{diff['breakage_events']} & {value_label} \\\\"
        )
        macros.append(command(prefix + "LambdaStar", value_label))
        macros.append(command(prefix + "LambdaPct",
                              f"{100 * value:.0f}\\%" if isinstance(value, float)
                              else "--"))
    assert total_defects == 0, f"clean matrix still has {total_defects} defects"
    macros.extend([
        command("CleanExecutorDefects", total_defects),
        command("CleanReserveRejects", total_reserve),
        command("CleanAssignAcceptanceBreaks", total_assign_acceptance_breaks),
        command("CleanMatrixRows", 4 * 4 * 150 * 3),
        command("CleanTotalCalls", f"{total_calls:,}"),
        command("CleanTotalTokens", f"{total_tokens:,}"),
        command("CausalRecoveryPairs", causal_recovery["n_target_pairs"]),
        command("SearchCandidateCount", search["n_candidates"]),
        command("SearchAssignInArchive", "yes" if search["assign_in_archive"] else "no"),
        command("SearchBestContainsAssign", "yes" if search["best_contains_assign"] else "no"),
        command("SearchLogicalCost", f"{search['search_usd_logical']:.2f}"),
    ])

    r = refiners
    assert r["math_audit"]["status"] == "passed"
    macros.extend([
        command("RefinerTaskCount", r["n"]),
        command("RefinerReferenceCorrect", r["reference_correct"]),
        command("RefinerFalseRejects", r["false_rejections"]),
        command("RefinerSharedExact", dec(r["shared_exact_ceiling"], 5)),
        command("RefinerSharedHoeffding", dec(r["shared_frr_hoeffding_ucb"], 5)),
    ])
    audited = r["cost"]["audited_decomposition"]
    gate = audited["shared_gate_pre_suffix"]
    suffix = r["cost"]["suffix_total"]
    savings = r["cost"]["shared_expost_savings_fraction"]
    macros.extend([
        command("SharedGateCalls", gate["calls"]),
        command("SharedGateTokens", f"{gate['tokens']:,}"),
        command("SharedGateSeconds", f"{gate['seconds']:.1f}"),
        command("FiveSuffixCalls", suffix["calls"]),
        command("FiveSuffixTokens", f"{suffix['tokens']:,}"),
        command("FiveSuffixSeconds", f"{suffix['seconds']:.1f}"),
        command("FiveSharedCallSavings", pct(savings["calls"])),
        command("FiveSharedTokenSavings", pct(savings["tokens"])),
        command("FiveSharedTimeSavings", pct(savings["seconds"])),
    ])

    def decision(screen: str, epsilon: float) -> dict:
        return next(x for x in r["screen_decisions"]
                    if x["screen"] == screen and abs(x["epsilon"] - epsilon) < 1e-12)

    for epsilon, suffix_name in ((.02, "Two"), (.05, "Five")):
        d = decision("shared_exact_fixed_prefix", epsilon)
        macros.extend([
            command("SharedPass" + suffix_name, d["candidates_screened_in_before_suffix"]),
            command("DirectPass" + suffix_name, d["direct_candidates_passing_after_suffix"]),
            command("SharedFalsePositive" + suffix_name, d["false_positive_count"]),
            command("SharedFalseNegative" + suffix_name, d["false_negative_count"]),
        ])

    refiner_rows: list[str] = []
    for key, label in REFINER_LABELS.items():
        row = r["refiners"][key]
        cost = row["cost"]
        direct = row["direct_stored_simultaneous_ucb"]
        refiner_rows.append(
            f"{label} & {cost['calls']} & {cost['tokens']:,} & "
            f"{row['repair_events']} & {row['breakage_events']} & "
            f"{row['length_terminated']} & {dec(direct, 5)} \\\\"
        )

    (PAPER / "generated_main_numbers.tex").write_text("\n".join(macros) + "\n")
    (PAPER / "generated_clean_matrix_rows.tex").write_text(
        "\n".join(matrix_rows[:-1] + [r"\bottomrule"]) + "\n")
    (PAPER / "generated_lambda_rows.tex").write_text(
        "\n".join(lambda_rows + [r"\bottomrule"]) + "\n")
    (PAPER / "generated_refiner5_rows.tex").write_text(
        "\n".join(refiner_rows + [r"\bottomrule"]) + "\n")
    print("wrote generated main-evidence LaTeX fragments")


if __name__ == "__main__":
    main()
